CC = gcc
FILES = addressTranslation.c addressTranslationTest.c

# JD: You went this far, you may as well have given your
#     executable a custom name  :)
build: $(FILES)
	$(CC) $(FILES)

clean:
	rm a.out
